"""Sandbox entrypoint for hu001 — generated by scripts/bundle_strategy.py.

Wraps poker_bot.strategies.hubase.choose_action(table, my_seat) in the
sandbox act(table) -> dict contract. assets/ holds the poker_bot package
tree, so internal imports work unmodified once assets/ is on sys.path.
importlib is used so pack.py's harness import-scanner does not flag
`poker_bot` as an unbundled module.
"""

import importlib
import os
import sys
from pathlib import Path

# assets/ is expected at ../assets relative to this file (harness/). Keep a
# fallback search in case the server extracts to a different layout.
for _candidate in [
    Path(__file__).resolve().parent.parent / "assets",
    Path(__file__).resolve().parent / "assets",
]:
    if (_candidate / "poker_bot").is_dir():
        if str(_candidate) not in sys.path:
            sys.path.insert(0, str(_candidate))
        break

os.environ.setdefault("POKER_RANGE_STATE_DIR", "/tmp/poker-range-state")

_strategy = importlib.import_module("poker_bot.strategies.hubase")
_choose_action = _strategy.choose_action

# In-memory opponent profiling: the sandbox has no app-side opponent store,
# so profiles are rebuilt from recentEvents across the match (module state
# persists between act() calls within a run).
try:
    _tracker = importlib.import_module("poker_bot.sandbox_opponent_tracker")
    _enrich_table = _tracker.enrich_table
except Exception:
    _tracker = None
    _enrich_table = None
try:
    _agent_stats = importlib.import_module("poker_bot.sandbox_agent_stats")
except Exception:
    _agent_stats = None

_diag_remaining = 0  # tag the first decisions' traces with prior diagnostics


def _my_seat(table):
    self_no = table.get("selfSeatNumber")
    for seat in table.get("seats", []):
        if seat.get("seatNumber") == self_no:
            return seat
    # Fallback: the seat holding hole cards is ours.
    for seat in table.get("seats", []):
        if seat.get("holeCards"):
            return seat
    return {}


def _clamp(amount, rng):
    lo, hi = rng.get("min"), rng.get("max")
    if lo is not None and amount < lo:
        amount = lo
    if hi is not None and hi > 0 and amount > hi:
        amount = hi
    return amount


def _fallback(table):
    """Cheapest legal action if the strategy throws."""
    available = (table.get("allowedActions") or {}).get("availableActions", [])
    for verb in ("check", "call", "fold"):
        if verb in available:
            return {"action": verb}
    return {"action": "fold"}


def act(table):
    """Sandbox contract: table dict in, action dict out.

    amount is the TOTAL committed this street (to-amount semantics), only
    included for bet/raise, clamped to the offered range. The runner
    legalizes anyway; the clamp just avoids leaning on that.
    """
    if _enrich_table is not None:
        try:
            table = _enrich_table(table)
        except Exception:
            pass  # profiles are an enhancement, never a dependency

    try:
        action, amount, message = _choose_action(table, _my_seat(table))
    except Exception as exc:  # never forfeit a spot to a strategy bug
        out = _fallback(table)
        out["reasoning_text"] = "fallback: " + type(exc).__name__
        return out

    out = {"action": action}
    if action in ("bet", "raise") and amount is not None:
        allowed = table.get("allowedActions") or {}
        rng = allowed.get("raiseRange" if action == "raise" else "betRange") or {}
        out["amount"] = int(_clamp(int(amount), rng))
    if message:
        out["reasoning_text"] = str(message)[:500]

    # First few decisions carry a diagnostic tag so the decision trace
    # answers, from inside the sandbox: did the prior table ship, are
    # live-fetch credentials present, and do seats expose real agent ids.
    global _diag_remaining
    if _diag_remaining > 0:
        _diag_remaining -= 1
        parts = []
        try:
            if _agent_stats is not None:
                parts.append(_agent_stats.prior_status())
            if _tracker is not None:
                parts.append(_tracker.debug_status())
        except Exception:
            pass
        if parts:
            tag = " [" + " | ".join(parts) + "]"
            out["reasoning_text"] = (out.get("reasoning_text") or "")[:300] + tag
    return out
